
DROP TABLE IF EXISTS `disease_info`;
CREATE TABLE `disease_info` (
                                `disease_id` VARCHAR(50) NOT NULL,
                                `disease_name` VARCHAR(255) NOT NULL,
                                PRIMARY KEY (`disease_id`)
);

INSERT INTO `disease_info` (`disease_id`, `disease_name`) VALUES
                                                              ('PA445553', 'Rheumatic Heart Disease'),
                                                              ('PA444910', 'Memory impairment'),
                                                              ('PA443421', 'Arrhythmias, Cardiac'),
                                                              ('PA166129534', 'time above therapeutic range'),
                                                              ('PA446443', 'Liver Failure, Acute'),
                                                              ('PA444761', 'Leukemia, Myeloid'),
                                                              ('PA444398', 'Hematoma, Subdural'),
                                                              ('PA444154', 'Fatty Liver'),
                                                              ('PA444552', 'Hypertension'),
                                                              ('PA166124372', 'treatment modification'),
                                                              ('PA443532', 'Bone Diseases'),
                                                              ('PA166183774', 'short qt syndrome 1'),
                                                              ('PA443933', 'Down Syndrome'),
                                                              ('PA446199', 'Overdose'),
                                                              ('PA444756', 'Lymphoid Leukemia'),
                                                              ('PA166123366', 'event-free survival'),
                                                              ('PA166129558', 'aggression'),
                                                              ('PA166123755', 'delayed graft function'),
                                                              ('PA443343', 'Anemia, Hemolytic'),
                                                              ('PA443797', 'Coronary Disease'),
                                                              ('PA166224501', 'eosinophilic esophagitis'),
                                                              ('PA162373099', 'Skeletal Dysplasia'),
                                                              ('PA444083', 'Erythema'),
                                                              ('PA445019', 'Myocardial Infarction'),
                                                              ('PA443842', 'Death'),
                                                              ('PA166123431', 'heart valve replacement'),
                                                              ('PA444257', 'Gastrointestinal Neoplasms'),
                                                              ('PA445218', 'Pancreatic Neoplasms'),
                                                              ('PA444607', 'Inappropriate ADH Syndrome'),
                                                              ('PA445043', 'Opioid-Related Disorders'),
                                                              ('PA445042', 'Narcolepsy'),
                                                              ('PA444239', 'Galactorrhea'),
                                                              ('PA445850', 'Thrombosis'),
                                                              ('PA166128121', 'cardiotoxicity'),
                                                              ('PA166114942', 'familial hypercholesterolemia'),
                                                              ('PA447127', 'Lewy Body Disease'),
                                                              ('PA447247', 'liver transplantation'),
                                                              ('PA445555', 'Rheumatic Diseases'),
                                                              ('PA444555', 'Hypertension, Pulmonary'),
                                                              ('PA446654', 'Cholangiocarcinoma'),
                                                              ('PA443450', 'Asthma'),
                                                              ('PA166120927', 'drug reaction with eosinophilia and systemic symptoms'),
                                                              ('PA166048829', 'Elderly Adult'),
                                                              ('PA444823', 'Lupus Nephritis'),
                                                              ('PA447321', 'Depressive Disorder, Major'),
                                                              ('PA443433', 'Juvenile Rheumatoid Arthritis'),
                                                              ('PA166122772', 'Paroxysmal nocturnal hemoglobinuria'),
                                                              ('PA447178', 'Pulmonary Disease, Chronic Obstructive'),
                                                              ('PA446862', 'Hepatitis B, Chronic'),
                                                              ('PA153906318', 'Autism Spectrum Disorder'),
                                                              ('PA444818', 'Lung Neoplasms'),
                                                              ('PA445828', 'Testicular Neoplasms'),
                                                              ('PA166048807', 'Behcet Syndrome'),
                                                              ('PA445391', 'Postoperative Complications'),
                                                              ('PA447215', 'Psychotic Disorder'),
                                                              ('PA162263525', 'Neuropathic pain'),
                                                              ('PA443833', 'Cystitis'),
                                                              ('PA166170245', 'Febrile neutropenia'),
                                                              ('PA444065', 'Epilepsy'),
                                                              ('PA445659', 'Sick Sinus Syndrome'),
                                                              ('PA447197', 'Attention Deficit Disorder with Hyperactivity'),
                                                              ('PA444510', 'Hyperalgesia'),
                                                              ('PA444760', 'Leukemia, Myeloid, Acute'),
                                                              ('PA166264221', 'Diminished ability to concentrate'),
                                                              ('PA445452', 'Psychomotor Agitation'),
                                                              ('PA447076', 'Headache Disorders'),
                                                              ('PA445221', 'Pancytopenia'),
                                                              ('PA445210', 'Pain, Postoperative'),
                                                              ('PA447212', 'Panic Disorder'),
                                                              ('PA447264', 'heparin-induced thrombocytopenia'),
                                                              ('PA159018367', 'Brugada syndrome'),
                                                              ('PA443512', 'Urinary Bladder Neoplasms'),
                                                              ('PA166165020', 'adverse cardiovascular events'),
                                                              ('PA446051', 'Vomiting'),
                                                              ('PA444485', 'Hodgkin Disease'),
                                                              ('PA444516', 'Hypercholesterolemia'),
                                                              ('PA446286', 'Spina Bifida Cystica'),
                                                              ('PA446264', 'Urinary Retention'),
                                                              ('PA165817016', 'Kidney Transplantation'),
                                                              ('PA443459', 'Atrial Fibrillation'),
                                                              ('PA444745', 'Leprosy'),
                                                              ('PA445131', 'Obesity'),
                                                              ('PA166159953', 'dose reduction'),
                                                              ('PA443448', 'Asthenia'),
                                                              ('PA446175', 'Leukemia, Myeloid, Chronic, Atypical, BCR-ABL Negative'),
                                                              ('PA445848', 'Thromboembolism'),
                                                              ('PA157379134', 'Myalgia'),
                                                              ('PA166185626', 'Somnolence'),
                                                              ('PA166123756', 'creatinine clearance'),
                                                              ('PA443560', 'Breast Neoplasms'),
                                                              ('PA447230', 'HIV Infections'),
                                                              ('PA166114457', 'lung transplantation'),
                                                              ('PA166129521', 'sedation'),
                                                              ('PA444575', 'Hyponatremia'),
                                                              ('PA160680212', 'Lymphoma, Large B-Cell, Diffuse'),
                                                              ('PA443362', 'Angina Pectoris'),
                                                              ('PA445217', 'Exocrine Pancreatic Insufficiency'),
                                                              ('PA446892', 'Hyperhomocysteinemia'),
                                                              ('PA444366', 'Heart Block'),
                                                              ('PA444845', 'Lymphoma, Non-Hodgkin'),
                                                              ('PA445468', 'Pulmonary Fibrosis'),
                                                              ('PA443875', 'Dermatitis'),
                                                              ('PA445376', 'Polycystic Ovary Syndrome'),
                                                              ('PA166123006', 'interstitial fibrosis'),
                                                              ('PA445768', 'Substance Withdrawal Syndrome'),
                                                              ('PA445301', 'Peripheral Nervous System Diseases'),
                                                              ('PA446745', 'Breast Neoplasms, Male'),
                                                              ('PA443332', 'Amyotrophic Lateral Sclerosis'),
                                                              ('PA446861', 'Hepatitis, Autoimmune'),
                                                              ('PA444282', 'Open-angle glaucoma'),
                                                              ('PA443626', 'Carcinoma, Squamous Cell'),
                                                              ('PA165108622', 'Drug interaction with drug'),
                                                              ('PA447109', 'Myopathies, Structural, Congenital'),
                                                              ('PA166128365', 'bone density'),
                                                              ('PA445172', 'Osteitis Deformans'),
                                                              ('PA447054', 'Stroke'),
                                                              ('PA445100', 'Neuroblastoma'),
                                                              ('PA166128826', 'multi-core congenital myopathy'),
                                                              ('PA444447', 'Hepatocellular Carcinoma'),
                                                              ('PA444684', 'Kidney Failure, Chronic'),
                                                              ('PA445724', 'Spondylitis, Ankylosing'),
                                                              ('PA166120929', 'severe cutaneous adverse reactions'),
                                                              ('PA166123311', 'catecholaminergic polymorphic ventricular tachycardia'),
                                                              ('PA444437', 'Hepatitis B'),
                                                              ('PA446827', 'Hematologic Neoplasms'),
                                                              ('PA166163391', 'statin-related myopathy'),
                                                              ('PA445503', 'Rectal Neoplasms'),
                                                              ('PA447322', 'therapy-related acute myeloid leukemia (t-ML)'),
                                                              ('PA445968', 'Turner Syndrome'),
                                                              ('PA166232141', 'Amplification of sexual behavior'),
                                                              ('PA443672', 'Transient Ischemic Attack'),
                                                              ('PA445876', 'Tobacco Use Disorder'),
                                                              ('PA166048926', 'Lead Poisoning, Nervous System, Childhood'),
                                                              ('PA444329', 'Graves Disease'),
                                                              ('PA165108952', 'Li-Fraumeni syndrome'),
                                                              ('PA445113', 'Neutropenia'),
                                                              ('PA445030', 'Myotonia'),
                                                              ('PA444067', 'Epilepsy, idiopathic generalized'),
                                                              ('PA445451', 'Psoriasis'),
                                                              ('PA166048814', 'Hyperuricemia'),
                                                              ('PA443286', 'Adrenal Hyperplasia, Congenital'),
                                                              ('PA443228', 'Abortion, Habitual'),
                                                              ('PA166163563', 'high on-treatment platelet reactivity'),
                                                              ('PA445992', 'Urinary Tract Infections'),
                                                              ('PA134850491', 'Transplantation'),
                                                              ('PA443355', 'Anemia, Sickle Cell'),
                                                              ('PA446761', 'Arthralgia'),
                                                              ('PA445187', 'Osteonecrosis'),
                                                              ('PA445689', 'Sleep Disorders'),
                                                              ('PA444617', 'Infertility disorder'),
                                                              ('PA443523', 'Blood Coagulation Disorders'),
                                                              ('PA444840', 'Lymphoma'),
                                                              ('PA443557', 'Brain Neoplasms'),
                                                              ('PA443367', 'Fabry Disease'),
                                                              ('PA166127658', 'Recurrence free survival'),
                                                              ('PA446847', 'Arrhythmogenic Right Ventricular Dysplasia'),
                                                              ('PA445254', 'Parkinson Disease'),
                                                              ('PA444368', 'Heart Diseases'),
                                                              ('PA166176306', 'Cognitive disorder'),
                                                              ('PA446615', 'Rhabdomyosarcoma, Alveolar'),
                                                              ('PA166179129', 'exacerbation of asthma'),
                                                              ('PA445190', 'Osteoporosis'),
                                                              ('PA445174', 'Osteoarthritis'),
                                                              ('PA443658', 'Central Nervous System Infectious Disorder'),
                                                              ('PA445204', 'Ovarian Neoplasms'),
                                                              ('PA166122649', 'Butyrylcholinesterase deficiency'),
                                                              ('PA447325', 'Coronary Restenosis'),
                                                              ('PA445428', 'Protein Deficiency'),
                                                              ('PA446304', 'Lymphoma, B-Cell'),
                                                              ('PA166123368', 'schizoaffective disorder'),
                                                              ('PA446411', 'Endometrial Neoplasms'),
                                                              ('PA166152644', 'schizencephaly'),
                                                              ('PA150527845', 'Persistent Hyperinsulinemia Hypoglycemia of Infancy'),
                                                              ('PA444460', 'Heroin Dependence'),
                                                              ('PA445566', 'Rickets'),
                                                              ('PA443685', 'Uterine Cervical Neoplasms'),
                                                              ('PA444522', 'Hyperglycemia'),
                                                              ('PA444859', 'Malaria'),
                                                              ('PA444370', 'Heart Failure'),
                                                              ('PA445802', 'Tachycardia'),
                                                              ('PA444320', 'Graft vs Host Disease'),
                                                              ('PA444250', 'Gastritis'),
                                                              ('PA443460', 'Atrial Flutter'),
                                                              ('PA165817398', 'Myelosuppression'),
                                                              ('PA445109', 'Neuromyelitis Optica'),
                                                              ('PA166123369', 'electrocardiogram qt prolonged'),
                                                              ('PA164925725', 'Toxic liver disease'),
                                                              ('PA444153', 'Fatigue'),
                                                              ('PA443309', 'Alcoholism'),
                                                              ('PA444804', 'Liver cancer'),
                                                              ('PA166123046', 'Smoking Cessation'),
                                                              ('PA166160459', 'international normalized ratio variability (inr-var)'),
                                                              ('PA165108401', 'Acute coronary syndrome'),
                                                              ('PA444417', 'Hemorrhage'),
                                                              ('PA445746', 'Stomatitis'),
                                                              ('PA166124386', 'Gastrointestinal toxicity'),
                                                              ('PA444327', 'Granulomatous Disease, Chronic'),
                                                              ('PA443761', 'Colorectal Neoplasms, Hereditary Nonpolyposis'),
                                                              ('PA445293', 'Familial Mediterranean Fever'),
                                                              ('PA446438', 'Kidney Failure'),
                                                              ('PA443407', 'Apnea'),
                                                              ('PA444937', 'Mesothelioma'),
                                                              ('PA447310', 'Vision Disorders'),
                                                              ('PA444380', 'Heartburn'),
                                                              ('PA445597', 'Sarcoma, Ewing''s'),
                                                              ('PA443250', 'Acquired Immunodeficiency Syndrome'),
                                                              ('PA134850558', 'Macular Degeneration'),
                                                              ('PA444939', 'Metabolism, Inborn Errors'),
                                                              ('PA444802', 'Liver Diseases, Alcoholic'),
                                                              ('PA444821', 'Lupus Erythematosus, Discoid'),
                                                              ('PA444167', 'Fetal Alcohol Syndrome'),
                                                              ('PA443227', 'Abortion, Spontaneous'),
                                                              ('PA443936', 'Drug Hypersensitivity'),
                                                              ('PA165108779', 'Migraine disorder'),
                                                              ('PA444685', 'Kidney Neoplasms'),
                                                              ('PA444650', 'Jaundice, Neonatal'),
                                                              ('PA166123203', 'intragastric ph'),
                                                              ('PA444819', 'Lupus erythematosus'),
                                                              ('PA166048714', 'Pregnancy'),
                                                              ('PA444418', 'Gastrointestinal Hemorrhage'),
                                                              ('PA443937', 'Drug Toxicity'),
                                                              ('PA444101', 'Esophageal Neoplasms'),
                                                              ('PA445013', 'Myelodysplastic Syndromes'),
                                                              ('PA443297', 'Agranulocytosis'),
                                                              ('PA446459', 'Myocardial Ischemia'),
                                                              ('PA445647', 'Shock, Septic'),
                                                              ('PA444591', 'Hypoventilation'),
                                                              ('PA446169', 'Leukemia, Lymphocytic, Chronic, B-Cell'),
                                                              ('PA166180841', 'renal transplant failure'),
                                                              ('PA444645', 'Ischemia'),
                                                              ('PA165108110', 'Dyslipidaemia'),
                                                              ('PA166195784', 'Chronic lung allograft dysfunction'),
                                                              ('PA166048848', 'Menopause'),
                                                              ('PA444477', 'von Hippel-Lindau Disease'),
                                                              ('PA443829', 'Cystic Fibrosis'),
                                                              ('PA443803', 'Cough'),
                                                              ('PA446155', 'Precursor Cell Lymphoblastic Leukemia-Lymphoma'),
                                                              ('PA145069467', 'Hearing Loss'),
                                                              ('PA166197121', 'COVID-19'),
                                                              ('PA166153403', 'gastroesophageal cancer'),
                                                              ('PA166185295', 'dysphoria'),
                                                              ('PA444435', 'Hepatitis'),
                                                              ('PA444284', 'Glioma'),
                                                              ('PA444400', 'Hematuria'),
                                                              ('PA166170534', 'complete early virological response'),
                                                              ('PA444606', 'Erectile Dysfunction'),
                                                              ('PA443782', 'Constipation'),
                                                              ('PA447300', 'Acquired Long QT Syndrome (aLQTS)'),
                                                              ('PA444626', 'Insulin Resistance'),
                                                              ('PA443750', 'Colitis, Ulcerative'),
                                                              ('PA443580', 'Burkitt Lymphoma'),
                                                              ('PA166048851', 'Purpura, Thrombocytopenic, Idiopathic'),
                                                              ('PA447276', 'Thrombosis of cerebral veins'),
                                                              ('PA446479', 'Hypertrophy, Left Ventricular'),
                                                              ('PA166169457', 'tonsillectomy'),
                                                              ('PA445018', 'Cardiomyopathies'),
                                                              ('PA443895', 'Diabetic Retinopathy'),
                                                              ('PA445506', 'Recurrence'),
                                                              ('PA444773', 'Leukopenia'),
                                                              ('PA166129532', 'time to therapeutic inr'),
                                                              ('PA445062', 'Neoplasms'),
                                                              ('PA166114455', 'acute cellular rejection'),
                                                              ('PA447196', 'Anxiety Disorders'),
                                                              ('PA445965', 'Tuberous Sclerosis'),
                                                              ('PA447048', 'Myopathy, Central Core'),
                                                              ('PA445465', 'Pulmonary Embolism'),
                                                              ('PA445975', 'Unconsciousness'),
                                                              ('PA162263534', 'Ototoxicity'),
                                                              ('PA166123298', 'over-anticoagulation'),
                                                              ('PA443364', 'Angina, Unstable'),
                                                              ('PA443888', 'Diabetes Mellitus, Type 1'),
                                                              ('PA443742', 'Cluster Headache'),
                                                              ('PA165857066', 'Anemia, Hemolytic, Congenital Nonspherocytic'),
                                                              ('PA165109162', 'Bronchopulmonary dysplasia of newborn'),
                                                              ('PA444997', 'Muscular Diseases'),
                                                              ('PA444987', 'Multiple Sclerosis'),
                                                              ('PA443737', 'Cleft Palate'),
                                                              ('PA443756', 'Colonic Neoplasms'),
                                                              ('PA166129530', 'time to achieve stable dose'),
                                                              ('PA166152848', 'hypertensive nephrosclerosis'),
                                                              ('PA445532', 'Retinal Diseases'),
                                                              ('PA443670', 'Cerebral Infarction'),
                                                              ('PA447216', 'Schizophrenia'),
                                                              ('PA445862', 'Thyrotoxicosis'),
                                                              ('PA444620', 'Inflammation'),
                                                              ('PA443553', 'Brain Diseases'),
                                                              ('PA446878', 'Cocaine dependence'),
                                                              ('PA446023', 'Vasculitis'),
                                                              ('PA444985', 'Multiple Myeloma'),
                                                              ('PA443324', 'Amenorrhea'),
                                                              ('PA162355520', 'Nephrolithiasis'),
                                                              ('PA444445', 'Hepatitis C'),
                                                              ('PA443464', 'Autoimmune Diseases'),
                                                              ('PA166159284', 'treatment interruptions'),
                                                              ('PA443736', 'Cleft Lip'),
                                                              ('PA443624', 'Renal Cell Carcinoma'),
                                                              ('PA166128807', 'biliary tract neoplasms'),
                                                              ('PA445004', 'Myasthenia Gravis'),
                                                              ('PA445999', 'Urticaria'),
                                                              ('PA445437', 'Pruritus'),
                                                              ('PA445676', 'Skin Diseases'),
                                                              ('PA445476', 'Purine-Pyrimidine Metabolism, Inborn Errors'),
                                                              ('PA443613', 'Basal Cell Carcinoma'),
                                                              ('PA443886', 'Diabetes Mellitus'),
                                                              ('PA443632', 'Cardiomyopathy, Dilated'),
                                                              ('PA445738', 'Stevens-Johnson Syndrome'),
                                                              ('PA443319', 'Alzheimer Disease'),
                                                              ('PA444367', 'Heart Defects, Congenital'),
                                                              ('PA445601', 'Osteosarcoma'),
                                                              ('PA446338', 'Neurofibromatosis 2'),
                                                              ('PA443657', 'Central Nervous System Diseases'),
                                                              ('PA444545', 'Hyperprolactinemia'),
                                                              ('PA443371', 'Angioedema'),
                                                              ('PA151958383', 'Gastrointestinal Stromal Tumors'),
                                                              ('PA444546', 'Hypersensitivity'),
                                                              ('PA443314', 'Alopecia'),
                                                              ('PA443223', 'Congenital Abnormalities'),
                                                              ('PA444339', 'Hallucinations'),
                                                              ('PA166170668', 'cns depression'),
                                                              ('PA444903', 'Melanoma'),
                                                              ('PA166123209', 'malaise'),
                                                              ('PA166131628', 'rapid virological response (rvr)'),
                                                              ('PA445146', 'Oliguria'),
                                                              ('PA446916', 'Sleep Apnea, Obstructive'),
                                                              ('PA443265', 'Adenocarcinoma'),
                                                              ('PA165374639', 'Suicide'),
                                                              ('PA446852', 'Hot Flashes'),
                                                              ('PA444822', 'Systemic lupus erythematosus'),
                                                              ('PA446038', 'Virus Diseases'),
                                                              ('PA166151827', 'adverse events'),
                                                              ('PA443853', 'Dementia'),
                                                              ('PA444342', 'Hamartoma Syndrome, Multiple'),
                                                              ('PA443815', 'Crohn Disease'),
                                                              ('PA444517', 'Hyperlipoproteinemia Type II'),
                                                              ('PA446771', 'Sepsis'),
                                                              ('PA446541', 'Lymphoma, Large-Cell, Anaplastic'),
                                                              ('PA445857', 'Thyroid Neoplasms'),
                                                              ('PA443994', 'Edema'),
                                                              ('PA166279881', 'elevated liver enzymes'),
                                                              ('PA443430', 'Arthritis'),
                                                              ('PA447146', 'Hyperammonemia'),
                                                              ('PA166115462', 'Dry mouth'),
                                                              ('PA445208', 'Pain'),
                                                              ('PA443335', 'Anaphylaxis'),
                                                              ('PA166307601', 'Dubin-Johnson syndrome'),
                                                              ('PA446876', 'Substance-Related Disorders'),
                                                              ('PA444750', 'Leukemia'),
                                                              ('PA445312', 'Pharyngitis'),
                                                              ('PA447209', 'Mood Disorder'),
                                                              ('PA446714', 'Residual Neoplasm'),
                                                              ('PA444863', 'Malignant Hyperthermia'),
                                                              ('PA446975', 'Neurotoxicity Syndromes'),
                                                              ('PA445084', 'Wilms Tumor'),
                                                              ('PA444584', 'Hypotensive disorder'),
                                                              ('PA443602', 'Marijuana Abuse'),
                                                              ('PA166124223', 'Pneumonitis'),
                                                              ('PA443705', 'Cholelithiasis'),
                                                              ('PA162370415', 'Metabolic Syndrome'),
                                                              ('PA445398', 'Pre-Eclampsia'),
                                                              ('PA447288', 'Essential hypertension'),
                                                              ('PA446004', 'Uterine Neoplasms'),
                                                              ('PA445425', 'Prostatic Neoplasms'),
                                                              ('PA446116', 'Inflammatory Bowel Diseases'),
                                                              ('PA445629', 'Seizures'),
                                                              ('PA446392', 'Malaria, Vivax'),
                                                              ('PA444898', 'Medulloblastoma'),
                                                              ('PA445687', 'Sleep Apnea Syndromes'),
                                                              ('PA443813', 'Crigler-Najjar Syndrome'),
                                                              ('PA445381', 'Adenomatous Polyposis Coli'),
                                                              ('PA165108889', 'Favism'),
                                                              ('PA444942', 'Methemoglobinemia'),
                                                              ('PA443425', 'Arteriosclerosis'),
                                                              ('PA444683', 'Kidney Failure, Acute'),
                                                              ('PA444938', 'Metabolic Diseases'),
                                                              ('PA444411', 'Hemolysis'),
                                                              ('PA444222', 'Fractures, Bone'),
                                                              ('PA446120', 'Hypertriglyceridemia'),
                                                              ('PA445403', 'Pregnancy Complications'),
                                                              ('PA447004', 'Migraine with Aura'),
                                                              ('PA166131629', 'sustained virological response (svr)'),
                                                              ('PA446661', 'Carcinoma, Small Cell'),
                                                              ('PA443582', 'Burns'),
                                                              ('PA443434', 'Arthritis, Rheumatoid'),
                                                              ('PA166048740', 'Helicobacter Infections'),
                                                              ('PA446214', 'Osteoporosis, Postmenopausal'),
                                                              ('PA445742', 'Stomach Neoplasms'),
                                                              ('PA444288', 'Glomerulonephritis, IGA'),
                                                              ('PA444059', 'Epidermal Necrolysis, Toxic'),
                                                              ('PA150516584', 'Homocysteinemia'),
                                                              ('PA444528', 'Hyperlipidemias'),
                                                              ('PA447163', 'Spondylarthropathies'),
                                                              ('PA444570', 'Hypoglycemia'),
                                                              ('PA166256642', 'Osteonecrosis of the jaw'),
                                                              ('PA165108357', 'Erythema multiforme NOS'),
                                                              ('PA166048887', 'Irritable Bowel Syndrome'),
                                                              ('PA166114377', 'Hand-foot syndrome'),
                                                              ('PA445086', 'Nephrosclerosis'),
                                                              ('PA445683', 'Skin Neoplasms'),
                                                              ('PA444354', 'Headache'),
                                                              ('PA166248341', 'primary graft failure'),
                                                              ('PA166123207', 'overall survival'),
                                                              ('PA444648', 'Jaundice'),
                                                              ('PA445769', 'Sudden Infant Death'),
                                                              ('PA446126', 'Tumor Lysis Syndrome'),
                                                              ('PA445759', 'Subarachnoid Hemorrhage'),
                                                              ('PA444281', 'Glaucoma'),
                                                              ('PA165111675', 'Drug Resistance'),
                                                              ('PA166048850', 'Soft Tissue Neoplasms'),
                                                              ('PA444066', 'Epilepsies, Partial'),
                                                              ('PA166252441', 'Primary central nervous system lymphoma'),
                                                              ('PA444109', 'Exanthema'),
                                                              ('PA446108', 'Colorectal Neoplasms'),
                                                              ('PA166128827', 'exertional rhabdomyolysis'),
                                                              ('PA443890', 'Diabetes Mellitus, Type 2'),
                                                              ('PA166186039', 'suicidal ideation'),
                                                              ('PA444807', 'Long QT Syndrome'),
                                                              ('PA166123507', 'Discontinuation'),
                                                              ('PA445549', 'Rhabdomyolysis'),
                                                              ('PA162263533', 'nephrotoxicity'),
                                                              ('PA133888799', 'Organ Transplantation'),
                                                              ('PA166120928', 'erythema exudativum multiforme'),
                                                              ('PA446028', 'Ventricular Fibrillation'),
                                                              ('PA443472', 'Back Pain'),
                                                              ('PA166129562', 'time below therapeutic range'),
                                                              ('PA443678', 'Cerebrovascular Disorders'),
                                                              ('PA166128371', 'platelet aggregation inhibition'),
                                                              ('PA447240', 'Peptic Ulcer'),
                                                              ('PA166122058', 'Mucositis'),
                                                              ('PA445526', 'Respiratory Tract Infections'),
                                                              ('PA444682', 'Kidney Diseases'),
                                                              ('PA446320', 'Lymphoma, T-Cell, Cutaneous'),
                                                              ('PA166129531', 'time in therapeutic range'),
                                                              ('PA444704', 'Premature Birth'),
                                                              ('PA444801', 'Liver Diseases'),
                                                              ('PA153619833', 'Peripheral Vascular Diseases'),
                                                              ('PA444395', 'Hematologic Disorder'),
                                                              ('PA444614', 'Infectious disease'),
                                                              ('PA443548', 'Bradycardia'),
                                                              ('PA166123766', 'platelet aggregation'),
                                                              ('PA445619', 'Scoliosis'),
                                                              ('PA445220', 'Pancreatitis'),
                                                              ('PA446171', 'Chronic myelogenous leukemia, BCR-ABL1 positive'),
                                                              ('PA444365', 'Cardiac Arrest'),
                                                              ('PA443997', 'Ehlers-Danlos Syndrome'),
                                                              ('PA446956', 'Serotonin Syndrome'),
                                                              ('PA445846', 'Thrombocytopenia'),
                                                              ('PA446900', 'Coagulation Protein Disorders'),
                                                              ('PA443851', 'Delirium'),
                                                              ('PA447211', 'Obsessive-Compulsive Disorder'),
                                                              ('PA447268', 'Tardive Dyskinesia'),
                                                              ('PA447050', 'Hypokalemic Periodic Paralysis'),
                                                              ('PA445787', 'Syncope'),
                                                              ('PA166123026', 'Progression-free survival'),
                                                              ('PA446366', 'Still''s Disease, Adult-Onset'),
                                                              ('PA166175756', 'cystic fibrosis pulmonary exacerbation'),
                                                              ('PA445048', 'Nausea'),
                                                              ('PA445538', 'Retinoblastoma'),
                                                              ('PA445941', 'Tuberculosis'),
                                                              ('PA446879', 'Alcohol-Related Disorders'),
                                                              ('PA445355', 'Pneumonia'),
                                                              ('PA162316739', 'Maculopapular Exanthema'),
                                                              ('PA444144', 'Fallopian Tube Neoplasms'),
                                                              ('PA445058', 'Metastatic neoplasm'),
                                                              ('PA446044', 'Vitamin D Deficiency'),
                                                              ('PA447218', 'Physiological sexual disorder'),
                                                              ('PA166123306', 'agitation'),
                                                              ('PA446974', 'Choroidal Neovascularization'),
                                                              ('PA444352', 'Head and Neck Neoplasms'),
                                                              ('PA165108308', 'Temporomandibular joint dysfunction syndrome'),
                                                              ('PA444283', 'Glioblastoma'),
                                                              ('PA166119041', 'drug-induced liver injury'),
                                                              ('PA446294', 'Torsades de Pointes'),
                                                              ('PA446021', 'Vascular Diseases'),
                                                              ('PA166114454', 'Transplant rejection'),
                                                              ('PA444511', 'Hyperbilirubinemia'),
                                                              ('PA443840', 'Deafness'),
                                                              ('PA446444', 'Low Back Pain'),
                                                              ('PA445009', 'Mycoses'),
                                                              ('PA443965', 'Dyspepsia'),
                                                              ('PA444977', 'Mucocutaneous Lymph Node Syndrome'),
                                                              ('PA443796', 'Coronary Artery Disease'),
                                                              ('PA447207', 'Depressive Disorder'),
                                                              ('PA446390', 'Malaria, Falciparum'),
                                                              ('PA446481', 'Kallmann Syndrome'),
                                                              ('PA445970', 'Typhoid Fever'),
                                                              ('PA446309', 'Lymphoma, T-Cell'),
                                                              ('PA166314441', 'surgery'),
                                                              ('PA165818136', 'Shortened QT interval'),
                                                              ('PA446336', 'Severe Combined Immunodeficiency'),
                                                              ('PA444178', 'Fever'),
                                                              ('PA445594', 'Sarcoma'),
                                                              ('PA444797', 'Liver Cirrhosis'),
                                                              ('PA443928', 'Dizziness'),
                                                              ('PA444104', 'Esophagitis'),
                                                              ('PA166248161', 'apnea of prematurity'),
                                                              ('PA447130', 'Myotonic Disorders'),
                                                              ('PA444145', 'Fanconi renotubular syndrome'),
                                                              ('PA447194', 'Agoraphobia'),
                                                              ('PA152530787', 'Diabetes, Permanent Neonatal (PNDM)'),
                                                              ('PA128406954', 'Weight gain'),
                                                              ('PA166205041', 'drug-induced lupus erythematosus due to hydralazine'),
                                                              ('PA444258', 'Gaucher Disease'),
                                                              ('PA443340', 'Anemia'),
                                                              ('PA445522', 'Respiratory Insufficiency'),
                                                              ('PA445046', 'Nasopharyngeal Neoplasms'),
                                                              ('PA446863', 'Hepatitis C, Chronic'),
                                                              ('PA445168', 'Oropharyngeal Neoplasms'),
                                                              ('PA445371', 'Poisoning'),
                                                              ('PA445273', 'Pemphigus'),
                                                              ('PA445095', 'Neural Tube Defects'),
                                                              ('PA446198', 'Arthritis, Psoriatic'),
                                                              ('PA446813', 'Gingival Overgrowth'),
                                                              ('PA446836', 'Disorder of facial skeleton'),
                                                              ('PA446713', 'Neuroendocrine Tumors'),
                                                              ('PA445016', 'Myeloproliferative Disorder'),
                                                              ('PA445316', 'Philadelphia Chromosome'),
                                                              ('PA446644', 'Adrenocortical Carcinoma'),
                                                              ('PA443940', 'Patent Ductus Arteriosus'),
                                                              ('PA444434', 'Hepatic Veno-Occlusive Disease'),
                                                              ('PA444589', 'Hypothyroidism'),
                                                              ('PA447208', 'Mental Disorders'),
                                                              ('PA445096', 'Neuralgia'),
                                                              ('PA446166', 'Precursor T-Cell Lymphoblastic Leukemia-Lymphoma'),
                                                              ('PA444949', 'Migraine without Aura'),
                                                              ('PA446432', 'Beta-thalassemia and related diseases'),
                                                              ('PA445089', 'Nephrotic Syndrome'),
                                                              ('PA445973', 'Ulcer'),
                                                              ('PA165108929', 'Binge eating disorder'),
                                                              ('PA166128095', 'treatment failure'),
                                                              ('PA445307', 'Peutz-Jeghers Syndrome'),
                                                              ('PA445917', 'Tremor'),
                                                              ('PA166114458', 'heart transplantation'),
                                                              ('PA447199', 'Bipolar Disorder'),
                                                              ('PA447278', 'Depression'),
                                                              ('PA446114', 'Arthritis, Gouty'),
                                                              ('PA166124406', 'platelet reactivity'),
                                                              ('PA165108809', 'Neonatal Abstinence Syndrome'),
                                                              ('PA165108853', 'Ovarian hyperstimulation syndrome'),
                                                              ('PA445431', 'Proteinuria'),
                                                              ('PA443894', 'Diabetic Neuropathies'),
                                                              ('PA446760', 'Multiple Endocrine Neoplasia Type 1'),
                                                              ('PA166170367', 'extrapyramidal symptoms'),
                                                              ('PA447298', 'venous thromboembolism'),
                                                              ('PA166119022', 'Methamphetamine dependence'),
                                                              ('PA131285571', 'aspirin-induced asthma'),
                                                              ('PA446065', 'Wegener Granulomatosis'),
                                                              ('PA447198', 'Autistic Disorder'),
                                                              ('PA446969', 'Venous Thrombosis'),
                                                              ('PA444848', 'Lymphopenia'),
                                                              ('PA443635', 'Cardiovascular Diseases'),
                                                              ('PA444318', 'Gout'),
                                                              ('PA166128188', 'systolic blood pressure'),
                                                              ('PA443636', 'Carotid Artery Diseases'),
                                                              ('PA444618', 'Infertility, Female'),
                                                              ('PA443622', 'Carcinoma, Non-Small-Cell Lung'),
                                                              ('PA444929', 'Mental Retardation'),
                                                              ('PA443970', 'Dystonia'),
                                                              ('PA443899', 'Diarrhea'),
                                                              ('PA166123307', 'Insomnia'),
                                                              ('PA446970', 'Postoperative Nausea and Vomiting'),
                                                              ('PA166169562', 'laparoscopic sleeve gastrectomy'),
                                                              ('PA166129560', 'Major Adverse Cardiac Events (MACE)'),
                                                              ('PA444255', 'Gastroesophageal Reflux'),
                                                              ('PA166123007', 'hematopoietic stem cell transplantation'),
                                                              ('PA445850', 'Thrombotic disease'),
                                                              ('PA443622', 'Non-Small Cell Lung Carcinoma'),
                                                              ('PA166120929', 'Severe Cutaneous Adverse Reactions'),
                                                              ('PA447321', 'Major Depressive Disorder'),
                                                              ('PA443309', 'Alcohol abuse'),
                                                              ('PA443434', 'Rheumatoid arthritis'),
                                                              ('PA444614', 'Infection'),
                                                              ('PA446863', 'Chronic hepatitis C virus infection'),
                                                              ('PA447230', 'HIV infectious disease'),
                                                              ('PA166114454', 'transplant rejection'),
                                                              ('PA166123507', 'discontinuation'),
                                                              ('PA166159953', 'Dose reduction'),
                                                              ('PA444395', 'Hematologic Diseases'),
                                                              ('PA444822', 'Lupus Erythematosus, Systemic'),
                                                              ('PA166119041', 'Drug-induced liver injury'),
                                                              ('PA166123431', 'Heart valve replacement'),
                                                              ('PA443421', 'Cardiac rhythm disease'),
                                                              ('PA444682', 'Kidney Disorder'),
                                                              ('PA444845', 'Non-Hodgkin Lymphoma'),
                                                              ('PA446155', 'Acute lymphoblastic leukemia'),
                                                              ('PA447247', 'Liver transplantation'),
                                                              ('PA166114457', 'Lung transplantation'),
                                                              ('PA166123026', 'progression-free survival'),
                                                              ('PA446171', 'Leukemia, Myelogenous, Chronic, BCR-ABL Positive'),
                                                              ('PA443635', 'Cardiovascular Disease'),
                                                              ('PA166123368', 'Schizoaffective disorder'),
                                                              ('PA443750', 'Ulcerative Colitis'),
                                                              ('PA166114942', 'Familial hypercholesterolemia'),
                                                              ('PA166115462', 'dry mouth'),
                                                              ('PA447215', 'Psychotic Disorders'),
                                                              ('PA447268', 'tardive dyskinesia'),
                                                              ('PA447298', 'Venous thromboembolism'),
                                                              ('PA446661', 'Small cell carcinoma'),
                                                              ('PA166114377', 'hand-foot syndrome'),
                                                              ('PA166122058', 'mucositis'),
                                                              ('PA166128121', 'Cardiotoxicity'),
                                                              ('PA444101', 'Neoplasm of esophagus'),
                                                              ('PA446432', 'beta-Thalassemia'),
                                                              ('PA446878', 'Cocaine-Related Disorders'),
                                                              ('PA447209', 'Mood Disorders'),
                                                              ('PA447240', 'Peptic Ulcer Disease'),
                                                              ('PA157379134', 'Myalgia unspecified'),
                                                              ('PA166114458', 'Heart transplantation'),
                                                              ('PA166123007', 'Hematopoietic stem cell transplantation'),
                                                              ('PA166185626', 'somnolence'),
                                                              ('PA443624', 'Carcinoma, Renal Cell'),
                                                              ('PA444445', 'Hepatitis C virus infection'),
                                                              ('PA131285571', 'Aspirin-induced asthma'),
                                                              ('PA443685', 'Uterine Cervical Neoplasm'),
                                                              ('PA166129560', 'major adverse cardiac events (mace)'),
                                                              ('PA443940', 'Ductus Arteriosus, Patent'),
                                                              ('PA444584', 'Hypotension'),
                                                              ('PA445058', 'Neoplasm Metastasis'),
                                                              ('PA166123307', 'insomnia'),
                                                              ('PA447198', 'Autism'),
                                                              ('PA152530787', 'Permanent Neonatal Diabetes'),
                                                              ('PA166120927', 'Drug Reaction with Eosinophilia and Systemic Symptoms'),
                                                              ('PA447218', 'Sexual Dysfunctions, Psychological'),
                                                              ('PA447048', 'Central Core Myopathy'),
                                                              ('PA166123046', 'cessation'),
                                                              ('PA166124386', 'gastrointestinal toxicity'),
                                                              ('PA444756', 'Leukemia, Lymphoid'),
                                                              ('PA443343', 'Hemolytic Anemia'),
                                                              ('PA165374639', 'suicide'),
                                                              ('PA443672', 'Ischemic Attack, Transient'),
                                                              ('PA166170245', 'febrile neutropenia'),
                                                              ('PA445857', 'Thyroid tumor'),
                                                              ('PA162263525', 'neuropathic pain'),
                                                              ('PA443433', 'Arthritis, Juvenile Rheumatoid'),
                                                              ('PA444802', 'Alcoholic Liver Diseases'),
                                                              ('PA162355520', 'nephrolithiasis'),
                                                              ('PA444447', 'Carcinoma, Hepatocellular'),
                                                              ('PA166124223', 'pneumonitis'),
                                                              ('PA444910', 'Memory Disorders');
