
DROP TABLE IF EXISTS `disease_info`;
CREATE TABLE `disease_info` (
                                `disease_id` VARCHAR(50) NOT NULL,
                                `disease_name` VARCHAR(255) NOT NULL,
                                PRIMARY KEY (`disease_id`)
);

INSERT INTO `disease_info` (`disease_id`, `disease_name`) VALUES
                                                              ('PA128406954', 'Weight gain'),
                                                              ('PA131285571', 'aspirin-induced asthma'),
                                                              ('PA133888799', 'Organ Transplantation'),
                                                              ('PA134850491', 'Transplantation'),
                                                              ('PA134850558', 'Macular Degeneration'),
                                                              ('PA145069467', 'Hearing Loss'),
                                                              ('PA150516584', 'Homocysteinemia'),
                                                              ('PA150527845', 'Persistent Hyperinsulinemia Hypoglycemia of Infancy'),
                                                              ('PA151958383', 'Gastrointestinal Stromal Tumors'),
                                                              ('PA152530787', 'Diabetes, Permanent Neonatal (PNDM)'),
                                                              ('PA153619833', 'Peripheral Vascular Diseases'),
                                                              ('PA153906318', 'Autism Spectrum Disorder'),
                                                              ('PA157379134', 'Myalgia'),
                                                              ('PA159018367', 'Brugada syndrome'),
                                                              ('PA160680212', 'Lymphoma, Large B-Cell, Diffuse'),
                                                              ('PA162263525', 'Neuropathic pain'),
                                                              ('PA162263533', 'nephrotoxicity'),
                                                              ('PA162263534', 'Ototoxicity'),
                                                              ('PA162316739', 'Maculopapular Exanthema'),
                                                              ('PA162355520', 'Nephrolithiasis'),
                                                              ('PA162370415', 'Metabolic Syndrome'),
                                                              ('PA162373099', 'Skeletal Dysplasia'),
                                                              ('PA164925725', 'Toxic liver disease'),
                                                              ('PA165108110', 'Dyslipidaemia'),
                                                              ('PA165108308', 'Temporomandibular joint dysfunction syndrome'),
                                                              ('PA165108357', 'Erythema multiforme NOS'),
                                                              ('PA165108401', 'Acute coronary syndrome'),
                                                              ('PA165108622', 'Drug interaction with drug'),
                                                              ('PA165108779', 'Migraine disorder'),
                                                              ('PA165108809', 'Neonatal Abstinence Syndrome'),
                                                              ('PA165108853', 'Ovarian hyperstimulation syndrome'),
                                                              ('PA165108889', 'Favism'),
                                                              ('PA165108929', 'Binge eating disorder'),
                                                              ('PA165108952', 'Li-Fraumeni syndrome'),
                                                              ('PA165109162', 'Bronchopulmonary dysplasia of newborn'),
                                                              ('PA165111675', 'Drug Resistance'),
                                                              ('PA165374639', 'Suicide'),
                                                              ('PA165817016', 'Kidney Transplantation'),
                                                              ('PA165817398', 'Myelosuppression'),
                                                              ('PA165818136', 'Shortened QT interval'),
                                                              ('PA165857066', 'Anemia, Hemolytic, Congenital Nonspherocytic'),
                                                              ('PA166048714', 'Pregnancy'),
                                                              ('PA166048740', 'Helicobacter Infections'),
                                                              ('PA166048807', 'Behcet Syndrome'),
                                                              ('PA166048814', 'Hyperuricemia'),
                                                              ('PA166048829', 'Elderly Adult'),
                                                              ('PA166048848', 'Menopause'),
                                                              ('PA166048850', 'Soft Tissue Neoplasms'),
                                                              ('PA166048851', 'Purpura, Thrombocytopenic, Idiopathic'),
                                                              ('PA166048887', 'Irritable Bowel Syndrome'),
                                                              ('PA166048926', 'Lead Poisoning, Nervous System, Childhood'),
                                                              ('PA166114377', 'Hand-foot syndrome'),
                                                              ('PA166114454', 'Transplant rejection'),
                                                              ('PA166114455', 'acute cellular rejection'),
                                                              ('PA166114457', 'lung transplantation'),
                                                              ('PA166114458', 'heart transplantation'),
                                                              ('PA166114942', 'familial hypercholesterolemia'),
                                                              ('PA166115462', 'Dry mouth'),
                                                              ('PA166119022', 'Methamphetamine dependence'),
                                                              ('PA166119041', 'drug-induced liver injury'),
                                                              ('PA166120927', 'drug reaction with eosinophilia and systemic symptoms'),
                                                              ('PA166120928', 'erythema exudativum multiforme'),
                                                              ('PA166120929', 'severe cutaneous adverse reactions'),
                                                              ('PA166122058', 'Mucositis'),
                                                              ('PA166122649', 'Butyrylcholinesterase deficiency'),
                                                              ('PA166122772', 'Paroxysmal nocturnal hemoglobinuria'),
                                                              ('PA166123006', 'interstitial fibrosis'),
                                                              ('PA166123007', 'hematopoietic stem cell transplantation'),
                                                              ('PA166123026', 'Progression-free survival'),
                                                              ('PA166123046', 'Smoking Cessation'),
                                                              ('PA166123203', 'intragastric ph'),
                                                              ('PA166123207', 'overall survival'),
                                                              ('PA166123209', 'malaise'),
                                                              ('PA166123298', 'over-anticoagulation'),
                                                              ('PA166123306', 'agitation'),
                                                              ('PA166123307', 'Insomnia'),
                                                              ('PA166123311', 'catecholaminergic polymorphic ventricular tachycardia'),
                                                              ('PA166123366', 'event-free survival'),
                                                              ('PA166123368', 'schizoaffective disorder'),
                                                              ('PA166123369', 'electrocardiogram qt prolonged'),
                                                              ('PA166123431', 'heart valve replacement'),
                                                              ('PA166123507', 'Discontinuation'),
                                                              ('PA166123755', 'delayed graft function'),
                                                              ('PA166123756', 'creatinine clearance'),
                                                              ('PA166123766', 'platelet aggregation'),
                                                              ('PA166124223', 'Pneumonitis'),
                                                              ('PA166124372', 'treatment modification'),
                                                              ('PA166124386', 'Gastrointestinal toxicity'),
                                                              ('PA166124406', 'platelet reactivity'),
                                                              ('PA166127658', 'Recurrence free survival'),
                                                              ('PA166128095', 'treatment failure'),
                                                              ('PA166128121', 'cardiotoxicity'),
                                                              ('PA166128188', 'systolic blood pressure'),
                                                              ('PA166128365', 'bone density'),
                                                              ('PA166128371', 'platelet aggregation inhibition'),
                                                              ('PA166128807', 'biliary tract neoplasms'),
                                                              ('PA166128826', 'multi-core congenital myopathy'),
                                                              ('PA166128827', 'exertional rhabdomyolysis'),
                                                              ('PA166129521', 'sedation'),
                                                              ('PA166129530', 'time to achieve stable dose'),
                                                              ('PA166129531', 'time in therapeutic range'),
                                                              ('PA166129532', 'time to therapeutic inr'),
                                                              ('PA166129534', 'time above therapeutic range'),
                                                              ('PA166129558', 'aggression'),
                                                              ('PA166129560', 'Major Adverse Cardiac Events (MACE)'),
                                                              ('PA166129562', 'time below therapeutic range'),
                                                              ('PA166131628', 'rapid virological response (rvr)'),
                                                              ('PA166131629', 'sustained virological response (svr)'),
                                                              ('PA166151827', 'adverse events'),
                                                              ('PA166152644', 'schizencephaly'),
                                                              ('PA166152848', 'hypertensive nephrosclerosis'),
                                                              ('PA166153403', 'gastroesophageal cancer'),
                                                              ('PA166159284', 'treatment interruptions'),
                                                              ('PA166159953', 'dose reduction'),
                                                              ('PA166160459', 'international normalized ratio variability (inr-var)'),
                                                              ('PA166163391', 'statin-related myopathy'),
                                                              ('PA166163563', 'high on-treatment platelet reactivity'),
                                                              ('PA166165020', 'adverse cardiovascular events'),
                                                              ('PA166169457', 'tonsillectomy'),
                                                              ('PA166169562', 'laparoscopic sleeve gastrectomy'),
                                                              ('PA166170245', 'Febrile neutropenia'),
                                                              ('PA166170367', 'extrapyramidal symptoms'),
                                                              ('PA166170534', 'complete early virological response'),
                                                              ('PA166170668', 'cns depression'),
                                                              ('PA166175756', 'cystic fibrosis pulmonary exacerbation'),
                                                              ('PA166176306', 'Cognitive disorder'),
                                                              ('PA166179129', 'exacerbation of asthma'),
                                                              ('PA166180841', 'renal transplant failure'),
                                                              ('PA166183774', 'short qt syndrome 1'),
                                                              ('PA166185295', 'dysphoria'),
                                                              ('PA166185626', 'Somnolence'),
                                                              ('PA166186039', 'suicidal ideation'),
                                                              ('PA166195784', 'Chronic lung allograft dysfunction'),
                                                              ('PA166197121', 'COVID-19'),
                                                              ('PA166205041', 'drug-induced lupus erythematosus due to hydralazine'),
                                                              ('PA166224501', 'eosinophilic esophagitis'),
                                                              ('PA166232141', 'Amplification of sexual behavior'),
                                                              ('PA166248161', 'apnea of prematurity'),
                                                              ('PA166248341', 'primary graft failure'),
                                                              ('PA166252441', 'Primary central nervous system lymphoma'),
                                                              ('PA166256642', 'Osteonecrosis of the jaw'),
                                                              ('PA166264221', 'Diminished ability to concentrate'),
                                                              ('PA166279881', 'elevated liver enzymes'),
                                                              ('PA166307601', 'Dubin-Johnson syndrome'),
                                                              ('PA166314441', 'surgery'),
                                                              ('PA443223', 'Congenital Abnormalities'),
                                                              ('PA443227', 'Abortion, Spontaneous'),
                                                              ('PA443228', 'Abortion, Habitual'),
                                                              ('PA443250', 'Acquired Immunodeficiency Syndrome'),
                                                              ('PA443265', 'Adenocarcinoma'),
                                                              ('PA443286', 'Adrenal Hyperplasia, Congenital'),
                                                              ('PA443297', 'Agranulocytosis'),
                                                              ('PA443309', 'Alcoholism'),
                                                              ('PA443314', 'Alopecia'),
                                                              ('PA443319', 'Alzheimer Disease'),
                                                              ('PA443324', 'Amenorrhea'),
                                                              ('PA443332', 'Amyotrophic Lateral Sclerosis'),
                                                              ('PA443335', 'Anaphylaxis'),
                                                              ('PA443340', 'Anemia'),
                                                              ('PA443343', 'Anemia, Hemolytic'),
                                                              ('PA443355', 'Anemia, Sickle Cell'),
                                                              ('PA443362', 'Angina Pectoris'),
                                                              ('PA443364', 'Angina, Unstable'),
                                                              ('PA443367', 'Fabry Disease'),
                                                              ('PA443371', 'Angioedema'),
                                                              ('PA443407', 'Apnea'),
                                                              ('PA443421', 'Arrhythmias, Cardiac'),
                                                              ('PA443425', 'Arteriosclerosis'),
                                                              ('PA443430', 'Arthritis'),
                                                              ('PA443433', 'Juvenile Rheumatoid Arthritis'),
                                                              ('PA443434', 'Arthritis, Rheumatoid'),
                                                              ('PA443448', 'Asthenia'),
                                                              ('PA443450', 'Asthma'),
                                                              ('PA443459', 'Atrial Fibrillation'),
                                                              ('PA443460', 'Atrial Flutter'),
                                                              ('PA443464', 'Autoimmune Diseases'),
                                                              ('PA443472', 'Back Pain'),
                                                              ('PA443512', 'Urinary Bladder Neoplasms'),
                                                              ('PA443523', 'Blood Coagulation Disorders'),
                                                              ('PA443532', 'Bone Diseases'),
                                                              ('PA443548', 'Bradycardia'),
                                                              ('PA443553', 'Brain Diseases'),
                                                              ('PA443557', 'Brain Neoplasms'),
                                                              ('PA443560', 'Breast Neoplasms'),
                                                              ('PA443580', 'Burkitt Lymphoma'),
                                                              ('PA443582', 'Burns'),
                                                              ('PA443602', 'Marijuana Abuse'),
                                                              ('PA443613', 'Basal Cell Carcinoma'),
                                                              ('PA443622', 'Carcinoma, Non-Small-Cell Lung'),
                                                              ('PA443624', 'Renal Cell Carcinoma'),
                                                              ('PA443626', 'Carcinoma, Squamous Cell'),
                                                              ('PA443632', 'Cardiomyopathy, Dilated'),
                                                              ('PA443635', 'Cardiovascular Diseases'),
                                                              ('PA443636', 'Carotid Artery Diseases'),
                                                              ('PA443657', 'Central Nervous System Diseases'),
                                                              ('PA443658', 'Central Nervous System Infectious Disorder'),
                                                              ('PA443670', 'Cerebral Infarction'),
                                                              ('PA443672', 'Transient Ischemic Attack'),
                                                              ('PA443678', 'Cerebrovascular Disorders'),
                                                              ('PA443685', 'Uterine Cervical Neoplasms'),
                                                              ('PA443705', 'Cholelithiasis'),
                                                              ('PA443736', 'Cleft Lip'),
                                                              ('PA443737', 'Cleft Palate'),
                                                              ('PA443742', 'Cluster Headache'),
                                                              ('PA443750', 'Colitis, Ulcerative'),
                                                              ('PA443756', 'Colonic Neoplasms'),
                                                              ('PA443761', 'Colorectal Neoplasms, Hereditary Nonpolyposis'),
                                                              ('PA443782', 'Constipation'),
                                                              ('PA443796', 'Coronary Artery Disease'),
                                                              ('PA443797', 'Coronary Disease'),
                                                              ('PA443803', 'Cough'),
                                                              ('PA443813', 'Crigler-Najjar Syndrome'),
                                                              ('PA443815', 'Crohn Disease'),
                                                              ('PA443829', 'Cystic Fibrosis'),
                                                              ('PA443833', 'Cystitis'),
                                                              ('PA443840', 'Deafness'),
                                                              ('PA443842', 'Death'),
                                                              ('PA443851', 'Delirium'),
                                                              ('PA443853', 'Dementia'),
                                                              ('PA443875', 'Dermatitis'),
                                                              ('PA443886', 'Diabetes Mellitus'),
                                                              ('PA443888', 'Diabetes Mellitus, Type 1'),
                                                              ('PA443890', 'Diabetes Mellitus, Type 2'),
                                                              ('PA443894', 'Diabetic Neuropathies'),
                                                              ('PA443895', 'Diabetic Retinopathy'),
                                                              ('PA443899', 'Diarrhea'),
                                                              ('PA443928', 'Dizziness'),
                                                              ('PA443933', 'Down Syndrome'),
                                                              ('PA443936', 'Drug Hypersensitivity'),
                                                              ('PA443937', 'Drug Toxicity'),
                                                              ('PA443940', 'Patent Ductus Arteriosus'),
                                                              ('PA443965', 'Dyspepsia'),
                                                              ('PA443970', 'Dystonia'),
                                                              ('PA443994', 'Edema'),
                                                              ('PA443997', 'Ehlers-Danlos Syndrome'),
                                                              ('PA444059', 'Epidermal Necrolysis, Toxic'),
                                                              ('PA444065', 'Epilepsy'),
                                                              ('PA444066', 'Epilepsies, Partial'),
                                                              ('PA444067', 'Epilepsy, idiopathic generalized'),
                                                              ('PA444083', 'Erythema'),
                                                              ('PA444101', 'Esophageal Neoplasms'),
                                                              ('PA444104', 'Esophagitis'),
                                                              ('PA444109', 'Exanthema'),
                                                              ('PA444144', 'Fallopian Tube Neoplasms'),
                                                              ('PA444145', 'Fanconi renotubular syndrome'),
                                                              ('PA444153', 'Fatigue'),
                                                              ('PA444154', 'Fatty Liver'),
                                                              ('PA444167', 'Fetal Alcohol Syndrome'),
                                                              ('PA444178', 'Fever'),
                                                              ('PA444222', 'Fractures, Bone'),
                                                              ('PA444239', 'Galactorrhea'),
                                                              ('PA444250', 'Gastritis'),
                                                              ('PA444255', 'Gastroesophageal Reflux'),
                                                              ('PA444257', 'Gastrointestinal Neoplasms'),
                                                              ('PA444258', 'Gaucher Disease'),
                                                              ('PA444281', 'Glaucoma'),
                                                              ('PA444282', 'Open-angle glaucoma'),
                                                              ('PA444283', 'Glioblastoma'),
                                                              ('PA444284', 'Glioma'),
                                                              ('PA444288', 'Glomerulonephritis, IGA'),
                                                              ('PA444318', 'Gout'),
                                                              ('PA444320', 'Graft vs Host Disease'),
                                                              ('PA444327', 'Granulomatous Disease, Chronic'),
                                                              ('PA444329', 'Graves Disease'),
                                                              ('PA444339', 'Hallucinations'),
                                                              ('PA444342', 'Hamartoma Syndrome, Multiple'),
                                                              ('PA444352', 'Head and Neck Neoplasms'),
                                                              ('PA444354', 'Headache'),
                                                              ('PA444365', 'Cardiac Arrest'),
                                                              ('PA444366', 'Heart Block'),
                                                              ('PA444367', 'Heart Defects, Congenital'),
                                                              ('PA444368', 'Heart Diseases'),
                                                              ('PA444370', 'Heart Failure'),
                                                              ('PA444380', 'Heartburn'),
                                                              ('PA444395', 'Hematologic Disorder'),
                                                              ('PA444398', 'Hematoma, Subdural'),
                                                              ('PA444400', 'Hematuria'),
                                                              ('PA444411', 'Hemolysis'),
                                                              ('PA444417', 'Hemorrhage'),
                                                              ('PA444418', 'Gastrointestinal Hemorrhage'),
                                                              ('PA444434', 'Hepatic Veno-Occlusive Disease'),
                                                              ('PA444435', 'Hepatitis'),
                                                              ('PA444437', 'Hepatitis B'),
                                                              ('PA444445', 'Hepatitis C'),
                                                              ('PA444447', 'Hepatocellular Carcinoma'),
                                                              ('PA444460', 'Heroin Dependence'),
                                                              ('PA444477', 'von Hippel-Lindau Disease'),
                                                              ('PA444485', 'Hodgkin Disease'),
                                                              ('PA444510', 'Hyperalgesia'),
                                                              ('PA444511', 'Hyperbilirubinemia'),
                                                              ('PA444516', 'Hypercholesterolemia'),
                                                              ('PA444517', 'Hyperlipoproteinemia Type II'),
                                                              ('PA444522', 'Hyperglycemia'),
                                                              ('PA444528', 'Hyperlipidemias'),
                                                              ('PA444545', 'Hyperprolactinemia'),
                                                              ('PA444546', 'Hypersensitivity'),
                                                              ('PA444552', 'Hypertension'),
                                                              ('PA444555', 'Hypertension, Pulmonary'),
                                                              ('PA444570', 'Hypoglycemia'),
                                                              ('PA444575', 'Hyponatremia'),
                                                              ('PA444584', 'Hypotensive disorder'),
                                                              ('PA444589', 'Hypothyroidism'),
                                                              ('PA444591', 'Hypoventilation'),
                                                              ('PA444606', 'Erectile Dysfunction'),
                                                              ('PA444607', 'Inappropriate ADH Syndrome'),
                                                              ('PA444614', 'Infectious disease'),
                                                              ('PA444617', 'Infertility disorder'),
                                                              ('PA444618', 'Infertility, Female'),
                                                              ('PA444620', 'Inflammation'),
                                                              ('PA444626', 'Insulin Resistance'),
                                                              ('PA444645', 'Ischemia'),
                                                              ('PA444648', 'Jaundice'),
                                                              ('PA444650', 'Jaundice, Neonatal'),
                                                              ('PA444682', 'Kidney Diseases'),
                                                              ('PA444683', 'Kidney Failure, Acute'),
                                                              ('PA444684', 'Kidney Failure, Chronic'),
                                                              ('PA444685', 'Kidney Neoplasms'),
                                                              ('PA444704', 'Premature Birth'),
                                                              ('PA444745', 'Leprosy'),
                                                              ('PA444750', 'Leukemia'),
                                                              ('PA444756', 'Lymphoid Leukemia'),
                                                              ('PA444760', 'Leukemia, Myeloid, Acute'),
                                                              ('PA444761', 'Leukemia, Myeloid'),
                                                              ('PA444773', 'Leukopenia'),
                                                              ('PA444797', 'Liver Cirrhosis'),
                                                              ('PA444801', 'Liver Diseases'),
                                                              ('PA444802', 'Liver Diseases, Alcoholic'),
                                                              ('PA444804', 'Liver cancer'),
                                                              ('PA444807', 'Long QT Syndrome'),
                                                              ('PA444818', 'Lung Neoplasms'),
                                                              ('PA444819', 'Lupus erythematosus'),
                                                              ('PA444821', 'Lupus Erythematosus, Discoid'),
                                                              ('PA444822', 'Systemic lupus erythematosus'),
                                                              ('PA444823', 'Lupus Nephritis'),
                                                              ('PA444840', 'Lymphoma'),
                                                              ('PA444845', 'Lymphoma, Non-Hodgkin'),
                                                              ('PA444848', 'Lymphopenia'),
                                                              ('PA444859', 'Malaria'),
                                                              ('PA444863', 'Malignant Hyperthermia'),
                                                              ('PA444898', 'Medulloblastoma'),
                                                              ('PA444903', 'Melanoma'),
                                                              ('PA444910', 'Memory impairment'),
                                                              ('PA444929', 'Mental Retardation'),
                                                              ('PA444937', 'Mesothelioma'),
                                                              ('PA444938', 'Metabolic Diseases'),
                                                              ('PA444939', 'Metabolism, Inborn Errors'),
                                                              ('PA444942', 'Methemoglobinemia'),
                                                              ('PA444949', 'Migraine without Aura'),
                                                              ('PA444977', 'Mucocutaneous Lymph Node Syndrome'),
                                                              ('PA444985', 'Multiple Myeloma'),
                                                              ('PA444987', 'Multiple Sclerosis'),
                                                              ('PA444997', 'Muscular Diseases'),
                                                              ('PA445004', 'Myasthenia Gravis'),
                                                              ('PA445009', 'Mycoses'),
                                                              ('PA445013', 'Myelodysplastic Syndromes'),
                                                              ('PA445016', 'Myeloproliferative Disorder'),
                                                              ('PA445018', 'Cardiomyopathies'),
                                                              ('PA445019', 'Myocardial Infarction'),
                                                              ('PA445030', 'Myotonia'),
                                                              ('PA445042', 'Narcolepsy'),
                                                              ('PA445043', 'Opioid-Related Disorders'),
                                                              ('PA445046', 'Nasopharyngeal Neoplasms'),
                                                              ('PA445048', 'Nausea'),
                                                              ('PA445058', 'Metastatic neoplasm'),
                                                              ('PA445062', 'Neoplasms'),
                                                              ('PA445084', 'Wilms Tumor'),
                                                              ('PA445086', 'Nephrosclerosis'),
                                                              ('PA445089', 'Nephrotic Syndrome'),
                                                              ('PA445095', 'Neural Tube Defects'),
                                                              ('PA445096', 'Neuralgia'),
                                                              ('PA445100', 'Neuroblastoma'),
                                                              ('PA445109', 'Neuromyelitis Optica'),
                                                              ('PA445113', 'Neutropenia'),
                                                              ('PA445131', 'Obesity'),
                                                              ('PA445146', 'Oliguria'),
                                                              ('PA445168', 'Oropharyngeal Neoplasms'),
                                                              ('PA445172', 'Osteitis Deformans'),
                                                              ('PA445174', 'Osteoarthritis'),
                                                              ('PA445187', 'Osteonecrosis'),
                                                              ('PA445190', 'Osteoporosis'),
                                                              ('PA445204', 'Ovarian Neoplasms'),
                                                              ('PA445208', 'Pain'),
                                                              ('PA445210', 'Pain, Postoperative'),
                                                              ('PA445217', 'Exocrine Pancreatic Insufficiency'),
                                                              ('PA445218', 'Pancreatic Neoplasms'),
                                                              ('PA445220', 'Pancreatitis'),
                                                              ('PA445221', 'Pancytopenia'),
                                                              ('PA445254', 'Parkinson Disease'),
                                                              ('PA445273', 'Pemphigus'),
                                                              ('PA445293', 'Familial Mediterranean Fever'),
                                                              ('PA445301', 'Peripheral Nervous System Diseases'),
                                                              ('PA445307', 'Peutz-Jeghers Syndrome'),
                                                              ('PA445312', 'Pharyngitis'),
                                                              ('PA445316', 'Philadelphia Chromosome'),
                                                              ('PA445355', 'Pneumonia'),
                                                              ('PA445371', 'Poisoning'),
                                                              ('PA445376', 'Polycystic Ovary Syndrome'),
                                                              ('PA445381', 'Adenomatous Polyposis Coli'),
                                                              ('PA445391', 'Postoperative Complications'),
                                                              ('PA445398', 'Pre-Eclampsia'),
                                                              ('PA445403', 'Pregnancy Complications'),
                                                              ('PA445425', 'Prostatic Neoplasms'),
                                                              ('PA445428', 'Protein Deficiency'),
                                                              ('PA445431', 'Proteinuria'),
                                                              ('PA445437', 'Pruritus'),
                                                              ('PA445451', 'Psoriasis'),
                                                              ('PA445452', 'Psychomotor Agitation'),
                                                              ('PA445465', 'Pulmonary Embolism'),
                                                              ('PA445468', 'Pulmonary Fibrosis'),
                                                              ('PA445476', 'Purine-Pyrimidine Metabolism, Inborn Errors'),
                                                              ('PA445503', 'Rectal Neoplasms'),
                                                              ('PA445506', 'Recurrence'),
                                                              ('PA445522', 'Respiratory Insufficiency'),
                                                              ('PA445526', 'Respiratory Tract Infections'),
                                                              ('PA445532', 'Retinal Diseases'),
                                                              ('PA445538', 'Retinoblastoma'),
                                                              ('PA445549', 'Rhabdomyolysis'),
                                                              ('PA445553', 'Rheumatic Heart Disease'),
                                                              ('PA445555', 'Rheumatic Diseases'),
                                                              ('PA445566', 'Rickets'),
                                                              ('PA445594', 'Sarcoma'),
                                                              ('PA445597', 'Sarcoma, Ewing''s'),
                                                              ('PA445601', 'Osteosarcoma'),
                                                              ('PA445619', 'Scoliosis'),
                                                              ('PA445629', 'Seizures'),
                                                              ('PA445647', 'Shock, Septic'),
                                                              ('PA445659', 'Sick Sinus Syndrome'),
                                                              ('PA445676', 'Skin Diseases'),
                                                              ('PA445683', 'Skin Neoplasms'),
                                                              ('PA445687', 'Sleep Apnea Syndromes'),
                                                              ('PA445689', 'Sleep Disorders'),
                                                              ('PA445724', 'Spondylitis, Ankylosing'),
                                                              ('PA445738', 'Stevens-Johnson Syndrome'),
                                                              ('PA445742', 'Stomach Neoplasms'),
                                                              ('PA445746', 'Stomatitis'),
                                                              ('PA445759', 'Subarachnoid Hemorrhage'),
                                                              ('PA445768', 'Substance Withdrawal Syndrome'),
                                                              ('PA445769', 'Sudden Infant Death'),
                                                              ('PA445787', 'Syncope'),
                                                              ('PA445802', 'Tachycardia'),
                                                              ('PA445828', 'Testicular Neoplasms'),
                                                              ('PA445846', 'Thrombocytopenia'),
                                                              ('PA445848', 'Thromboembolism'),
                                                              ('PA445850', 'Thrombosis'),
                                                              ('PA445857', 'Thyroid Neoplasms'),
                                                              ('PA445862', 'Thyrotoxicosis'),
                                                              ('PA445876', 'Tobacco Use Disorder'),
                                                              ('PA445917', 'Tremor'),
                                                              ('PA445941', 'Tuberculosis'),
                                                              ('PA445965', 'Tuberous Sclerosis'),
                                                              ('PA445968', 'Turner Syndrome'),
                                                              ('PA445970', 'Typhoid Fever'),
                                                              ('PA445973', 'Ulcer'),
                                                              ('PA445975', 'Unconsciousness'),
                                                              ('PA445992', 'Urinary Tract Infections'),
                                                              ('PA445999', 'Urticaria'),
                                                              ('PA446004', 'Uterine Neoplasms'),
                                                              ('PA446021', 'Vascular Diseases'),
                                                              ('PA446023', 'Vasculitis'),
                                                              ('PA446028', 'Ventricular Fibrillation'),
                                                              ('PA446038', 'Virus Diseases'),
                                                              ('PA446044', 'Vitamin D Deficiency'),
                                                              ('PA446051', 'Vomiting'),
                                                              ('PA446065', 'Wegener Granulomatosis'),
                                                              ('PA446108', 'Colorectal Neoplasms'),
                                                              ('PA446114', 'Arthritis, Gouty'),
                                                              ('PA446116', 'Inflammatory Bowel Diseases'),
                                                              ('PA446120', 'Hypertriglyceridemia'),
                                                              ('PA446126', 'Tumor Lysis Syndrome'),
                                                              ('PA446155', 'Precursor Cell Lymphoblastic Leukemia-Lymphoma'),
                                                              ('PA446166', 'Precursor T-Cell Lymphoblastic Leukemia-Lymphoma'),
                                                              ('PA446169', 'Leukemia, Lymphocytic, Chronic, B-Cell'),
                                                              ('PA446171', 'Chronic myelogenous leukemia, BCR-ABL1 positive'),
                                                              ('PA446175', 'Leukemia, Myeloid, Chronic, Atypical, BCR-ABL Negative'),
                                                              ('PA446198', 'Arthritis, Psoriatic'),
                                                              ('PA446199', 'Overdose'),
                                                              ('PA446214', 'Osteoporosis, Postmenopausal'),
                                                              ('PA446264', 'Urinary Retention'),
                                                              ('PA446286', 'Spina Bifida Cystica'),
                                                              ('PA446294', 'Torsades de Pointes'),
                                                              ('PA446304', 'Lymphoma, B-Cell'),
                                                              ('PA446309', 'Lymphoma, T-Cell'),
                                                              ('PA446320', 'Lymphoma, T-Cell, Cutaneous'),
                                                              ('PA446336', 'Severe Combined Immunodeficiency'),
                                                              ('PA446338', 'Neurofibromatosis 2'),
                                                              ('PA446366', 'Still''s Disease, Adult-Onset'),
                                                              ('PA446390', 'Malaria, Falciparum'),
                                                              ('PA446392', 'Malaria, Vivax'),
                                                              ('PA446411', 'Endometrial Neoplasms'),
                                                              ('PA446432', 'Beta-thalassemia and related diseases'),
                                                              ('PA446438', 'Kidney Failure'),
                                                              ('PA446443', 'Liver Failure, Acute'),
                                                              ('PA446444', 'Low Back Pain'),
                                                              ('PA446459', 'Myocardial Ischemia'),
                                                              ('PA446479', 'Hypertrophy, Left Ventricular'),
                                                              ('PA446481', 'Kallmann Syndrome'),
                                                              ('PA446541', 'Lymphoma, Large-Cell, Anaplastic'),
                                                              ('PA446615', 'Rhabdomyosarcoma, Alveolar'),
                                                              ('PA446644', 'Adrenocortical Carcinoma'),
                                                              ('PA446654', 'Cholangiocarcinoma'),
                                                              ('PA446661', 'Carcinoma, Small Cell'),
                                                              ('PA446713', 'Neuroendocrine Tumors'),
                                                              ('PA446714', 'Residual Neoplasm'),
                                                              ('PA446745', 'Breast Neoplasms, Male'),
                                                              ('PA446760', 'Multiple Endocrine Neoplasia Type 1'),
                                                              ('PA446761', 'Arthralgia'),
                                                              ('PA446771', 'Sepsis'),
                                                              ('PA446813', 'Gingival Overgrowth'),
                                                              ('PA446827', 'Hematologic Neoplasms'),
                                                              ('PA446836', 'Disorder of facial skeleton'),
                                                              ('PA446847', 'Arrhythmogenic Right Ventricular Dysplasia'),
                                                              ('PA446852', 'Hot Flashes'),
                                                              ('PA446861', 'Hepatitis, Autoimmune'),
                                                              ('PA446862', 'Hepatitis B, Chronic'),
                                                              ('PA446863', 'Hepatitis C, Chronic'),
                                                              ('PA446876', 'Substance-Related Disorders'),
                                                              ('PA446878', 'Cocaine dependence'),
                                                              ('PA446879', 'Alcohol-Related Disorders'),
                                                              ('PA446892', 'Hyperhomocysteinemia'),
                                                              ('PA446900', 'Coagulation Protein Disorders'),
                                                              ('PA446916', 'Sleep Apnea, Obstructive'),
                                                              ('PA446956', 'Serotonin Syndrome'),
                                                              ('PA446969', 'Venous Thrombosis'),
                                                              ('PA446970', 'Postoperative Nausea and Vomiting'),
                                                              ('PA446974', 'Choroidal Neovascularization'),
                                                              ('PA446975', 'Neurotoxicity Syndromes'),
                                                              ('PA447004', 'Migraine with Aura'),
                                                              ('PA447048', 'Myopathy, Central Core'),
                                                              ('PA447050', 'Hypokalemic Periodic Paralysis'),
                                                              ('PA447054', 'Stroke'),
                                                              ('PA447076', 'Headache Disorders'),
                                                              ('PA447109', 'Myopathies, Structural, Congenital'),
                                                              ('PA447127', 'Lewy Body Disease'),
                                                              ('PA447130', 'Myotonic Disorders'),
                                                              ('PA447146', 'Hyperammonemia'),
                                                              ('PA447163', 'Spondylarthropathies'),
                                                              ('PA447178', 'Pulmonary Disease, Chronic Obstructive'),
                                                              ('PA447194', 'Agoraphobia'),
                                                              ('PA447196', 'Anxiety Disorders'),
                                                              ('PA447197', 'Attention Deficit Disorder with Hyperactivity'),
                                                              ('PA447198', 'Autistic Disorder'),
                                                              ('PA447199', 'Bipolar Disorder'),
                                                              ('PA447207', 'Depressive Disorder'),
                                                              ('PA447208', 'Mental Disorders'),
                                                              ('PA447209', 'Mood Disorder'),
                                                              ('PA447211', 'Obsessive-Compulsive Disorder'),
                                                              ('PA447212', 'Panic Disorder'),
                                                              ('PA447215', 'Psychotic Disorder'),
                                                              ('PA447216', 'Schizophrenia'),
                                                              ('PA447218', 'Physiological sexual disorder'),
                                                              ('PA447230', 'HIV Infections'),
                                                              ('PA447240', 'Peptic Ulcer'),
                                                              ('PA447247', 'liver transplantation'),
                                                              ('PA447264', 'heparin-induced thrombocytopenia'),
                                                              ('PA447268', 'Tardive Dyskinesia'),
                                                              ('PA447276', 'Thrombosis of cerebral veins'),
                                                              ('PA447278', 'Depression'),
                                                              ('PA447288', 'Essential hypertension'),
                                                              ('PA447298', 'venous thromboembolism'),
                                                              ('PA447300', 'Acquired Long QT Syndrome (aLQTS)'),
                                                              ('PA447310', 'Vision Disorders'),
                                                              ('PA447321', 'Depressive Disorder, Major'),
                                                              ('PA447322', 'therapy-related acute myeloid leukemia (t-ML)'),
                                                              ('PA447325', 'Coronary Restenosis');
